services:
  - type: web
    name: tbk-vendas
    runtime: static
    staticPublishPath: .
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
